name: Sync Forks

on:
  schedule:
    - cron: '0 0 * * *'  # 每天同步一次
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.ACTIONS_PAT }}

    - name: Set up Git
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'

    - name: Add remote repositories
      run: |
        git remote add frogpilot https://github.com/FrogAi/FrogPilot
        git remote add sunnypilot https://github.com/sunnypilot/sunnypilot
        git remote add dragonpilot https://github.com/dragonpilot-community/dragonpilot
        git remote add opgm https://github.com/opgm/openpilot
        git remote add pfeiferj https://github.com/pfeiferj/pfeifer-pilot-patches
        git remote add twilsonco https://github.com/twilsonco/openpilot

    - name: Fetch and merge FrogPilot
      run: |
        git fetch frogpilot
        git checkout -B FrogPilot frogpilot/FrogPilot
        git push origin FrogPilot --force

    - name: Fetch and merge dev-c3
      run: |
        git fetch sunnypilot
        git checkout -B dev-c3 sunnypilot/dev-c3
        git push origin dev-c3 --force

    - name: Fetch and merge d3
      run: |
        git fetch dragonpilot
        git checkout -B d3 dragonpilot/d3
        git push origin d3 --force

    - name: Fetch and merge opgm
      run: |
        git fetch opgm
        git checkout -B build opgm/build
        git push origin build --force

    - name: Fetch and merge twilsonco
      run: |
        git fetch twilsonco
        git checkout -B tw-staging twilsonco/tw-staging
        git push origin tw-staging --force


    - name: Fetch and merge pfeiferj
      run: |
        git fetch pfeiferj
        git checkout -B pfeifer-pilot-patches pfeiferj/pfeifer-pilot-patches
        git push origin pfeifer-pilot-patches --force


